### ISSUE TITLE
이벤트 페이지 구현

### ISSUE THREAD

**Issue by Halozhan** [AISWProject/your_ear_fits#13]
스크롤 기능
컨테이너로 아래와 같이 구현하는게 목표
![Image](https://github.com/user-attachments/assets/040d15df-d1f7-4516-b84d-c40da38acabb)
![Image](https://github.com/user-attachments/assets/c9950cd8-785d-4c06-a382-bca2a6dd976b)

상세 내용은
![Image](https://github.com/user-attachments/assets/739028ad-e793-4a75-ae56-b7c845f48599)

**Comment by Halozhan** [comment]
https://github.com/AISWProject/your_ear_fits/pull/11

**Comment by ayanemoona** [comment]
멋쪄용

**Comment by fryti112** [comment]
![Image](https://github.com/user-attachments/assets/703bd0d6-3deb-4768-b60e-53914b8b5de3)



![Image](https://github.com/user-attachments/assets/b0559f0e-bd0c-4225-95e6-101041fdef06)

구현 이미지

**Comment by fryti112** [comment]
https://github.com/AISWProject/your_ear_fits/pull/15
